### ISSUE TITLE
tab切换类型的Fragement问题

### ISSUE THREAD

**Issue by lizhanqi** [yanzhenjie/NoFragment#7]
在做类似于微信tab切换的Fragement的时候,每次都会开启一个新的Fragement实例,这里我看源码好像就有这些问题(因为每次都是newInstance一个),能加入仅仅是一个Fragement的实例的方式吗?

**Comment by yanzhenjie** [comment]
切换Tab直接用原生就好了，干嘛还用NoFragment呢。另外就算BaseFragment是继承NoFragment也没有关系，用法完全和普通Fragment一样，没有说每次切换需要newInstacen.

**Comment by lizhanqi** [comment]
我用的时候感觉startFragment这种方式真的很便捷,
至于说每次切换都会是一个newInstacen,这里是您在startFragment方法中通过
NoFragment targetFragment = clazz.newInstance();方式生成的
如果我使用同一Fragement的实例对象,那么在      
fragmentTransaction.add(fragmentLayoutId(), thatFragment, fragmentTag);会异常,因为这个实例已经有了一个tag了

**Comment by yanzhenjie** [comment]
如果是`Tab`的形式，那么你把`Fragment`保存起来，然后每次`replace()`（不推荐）或者`add()/show()/hide()`，如果要已经被`add()`过了，应该调用`show()`。说的这些都是普通`Fragment`的用法，NoFragment只是提供了`startFragment()`这种方式，它是一个`Activity`多个`Fragment`的架构用的。
